# Generated by Django 4.2.5 on 2023-09-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('brand_image', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('intrest_level', models.IntegerField()),
                ('apllication_date', models.DateField()),
            ],
        ),
    ]
