# Generated by Django 4.2.5 on 2023-09-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='intrest_level',
            new_name='interest_level',
        ),
    ]
