# Generated by Django 4.2.5 on 2023-09-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_intrest_level_job_interest_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='apllication_date',
            new_name='aplication',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='brand_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='interest_level',
            new_name='interest',
        ),
    ]
