# Generated by Django 4.2.5 on 2023-09-26 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_apllication_date_job_aplication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='aplication',
            new_name='aplication_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='brand_image',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='interest',
            new_name='interest_level',
        ),
    ]
