# Generated by Django 4.2.5 on 2023-09-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_aplication_date_job_application_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='brand_image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(max_length=200),
        ),
    ]
