# Generated by Django 4.2.5 on 2023-09-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_brand_image_alter_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='brand_image',
            field=models.CharField(),
        ),
    ]
