# Generated by Django 4.2.5 on 2023-09-30 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_brand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='brand_image',
        ),
    ]
